schema = 3

[mod]
  [mod."github.com/tailscale/hujson"]
    version = "v0.0.0-20220506213045-af5ed07155e5"
    hash = "sha256-1GSk6EuOO9B8fnOZexSpTZpkxGxhKISmj57p7/2OjLM="
  [mod."github.com/tailscale/tailscale-client-go/v2"]
    version = "v2.0.0-20240920152217-9894791f98d9"
    hash = "sha256-odeWUTnv6ts59jMv2VeRjEweWpETPydulAtsi9svtI8="
  [mod."golang.org/x/oauth2"]
    version = "v0.21.0"
    hash = "sha256-0xgi5k7fxMScMH+rDwXhDqe8raTFHh5ih727jGVS918="
